teleop:
  piloting:
    type: topic
    message_type: "geometry_msgs/Twist"
    topic_name: cmd_vel
    deadman_buttons: [7]
    axis_mappings:
      -
        axis: 2  # Right thumb stick (up/down)
        target: linear.x
        scale: .5
        offset: 0.0
      -
        axis: 3  # Right thumb stick (left/right)
        target: linear.y
        scale: .5
        offset: 0.0
      -
        axis: 1  # Left thumb stick (up/down)
        target: linear.z
        scale: .5
        offset: 0.0
      -
        axis: 0  # Left thumb stick (left/right)
        target: angular.z
        scale: 0.5
        offset: 0.0
  camera:
    type: topic
    message_type: "geometry_msgs/Twist"
    topic_name: camera_control
    deadman_buttons: [7]
    axis_mappings:
      -
        axis: 5  # Left D-Pad (up/down)
        target: angular.y
        scale: 35.0
        offset: 0.0
      -
        axis: 4  # Left D-Pad (left/right)
        target: angular.z
        scale: -35.0
        offset: 0.0
  takeoff:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: takeoff
    deadman_buttons: [0, 7]  # RT + 1
    axis_mappings: []
  land:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: land
    deadman_buttons: [2, 7]  # RT + 3
    axis_mappings: []
  emergency:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: reset
    deadman_buttons: [8, 7] # RT + SEL
    axis_mappings: []
  flattrim:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: flattrim
    deadman_buttons: [9, 7] # RT +
    axis_mappings: []
  flip_forward:
    type: topic
    message_type: "std_msgs/UInt8"
    topic_name: flip
    deadman_buttons: [6, 7, 0] # RT + LT + 7
    axis_mappings: []
  snapshot:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: snapshot
    deadman_buttons: [7, 6, 2] # LT + RT + 3
    axis_mappings: []
